"""Span-by-span document editing.

Logic lives in submodules; this package re-exports the public API so callers
can keep using `from thaumaturgy import editing`. No NiceGUI here — the page
is presentation only.
"""

from thaumaturgy.editing.service import (
    ACCEPTED,
    DEFAULT_CONTEXT_FRAMING,
    DEFAULT_PASSAGE_INSTRUCTION,
    DEFAULT_PRIMED_REPLY,
    DEFAULT_SETTINGS,
    DEFAULT_SYSTEM_PROMPT,
    FLAGGED,
    INSTRUCTION_KEYS,
    ORIGINAL,
    PENDING,
    PROPOSED,
    assemble,
    budgets,
    build_messages,
    busy,
    cancel,
    check_output,
    create,
    decide,
    default_instructions,
    est_tokens,
    make_spans,
    next_pending,
    normalize_instructions,
    normalize_settings,
    oversized,
    pack_spans,
    prepare,
    progress,
    reattach_edges,
    record_result,
    sampler_params,
    split_atoms,
    split_span,
    start_span,
)
from thaumaturgy.editing.validator import (
    MIN_DRAWN_FROM_SOURCE,
    drawn_from_source,
    reaches_end,
    starts_at_start,
)

__all__ = [
    "ACCEPTED",
    "DEFAULT_CONTEXT_FRAMING",
    "DEFAULT_PASSAGE_INSTRUCTION",
    "DEFAULT_PRIMED_REPLY",
    "DEFAULT_SETTINGS",
    "DEFAULT_SYSTEM_PROMPT",
    "FLAGGED",
    "INSTRUCTION_KEYS",
    "MIN_DRAWN_FROM_SOURCE",
    "ORIGINAL",
    "PENDING",
    "PROPOSED",
    "assemble",
    "budgets",
    "build_messages",
    "busy",
    "cancel",
    "check_output",
    "create",
    "decide",
    "default_instructions",
    "drawn_from_source",
    "est_tokens",
    "make_spans",
    "next_pending",
    "normalize_instructions",
    "normalize_settings",
    "oversized",
    "pack_spans",
    "prepare",
    "progress",
    "reaches_end",
    "reattach_edges",
    "record_result",
    "sampler_params",
    "split_atoms",
    "split_span",
    "start_span",
    "starts_at_start",
]
